server:
  port: 8091

spring:
  cloud:
      stream:
        default-binder: kafka
        bindings:
          input:
            destination: srisai_producer_topic
            content_type: application/json

        kafka:
          binder:
            brokers: localhost:9092